### ISSUE TITLE
Database locked during `set_task_start` and `set_task_end` for large number of tasks

### ISSUE THREAD

**Issue by aplowman** [LightForm-group/hpcflow#15]
Given this workflow:

```yaml
scheduler: sge
output_dir: output
error_dir: output

command_groups:
  - commands: hpcflow dummy doSomething --infile1 infile_1.txt --infile2 infile_2.txt
    directory: <<sim_dir>>
  - commands: echo "This is a processing task."
    directory: <<sim_dir>>
  - commands: echo "Final task."
    directory: '.'

variables:
  sim_dir:
    file_regex:
      pattern: '(sims/[0-9]+$)'
      is_dir: true
      group: 0
    value: '{}'
```

and a large number of `sims/` subdirectories (tested with 41, e.g. `sims/0`, `sims/1`, ..., `sims/40`), and the following `reset.sh` script for setting up the input files:

```bash
rm -r .hpcflow output
find . -type f -name 'outfile*' -delete
find . -type f -name 'infile*' -delete

for d in sims/*; do
    cd $d
    hpcflow dummy makeSomething --name infile --num 2 ".txt" ".txt"
    cd ../..
done
```

The `hpcflow.api.set_task_start` and `hpcflow.api.set_task_end` commands during on `session.commit()` due to an sqlalchemy `OperationError` (locked database). Some exception handling and a while loop is required to fix this.
